"""empty message

Revision ID: 04e35c276340
Revises: 747c833d5f43
Create Date: 2023-10-17 13:08:30.111915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e35c276340'
down_revision = '747c833d5f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('main_image')
        batch_op.drop_column('additional_image2')
        batch_op.drop_column('additional_image1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_image1', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('additional_image2', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('main_image', sa.VARCHAR(length=150), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
