"""empty message

Revision ID: 747c833d5f43
Revises: 8dec847e24f5
Create Date: 2023-10-16 13:20:42.129571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '747c833d5f43'
down_revision = '8dec847e24f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('additional_image1', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('additional_image2', sa.String(length=150), nullable=False))
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('additional_image2')
        batch_op.drop_column('additional_image1')
        batch_op.drop_column('main_image')

    # ### end Alembic commands ###
