"""empty message

Revision ID: 8b1a545a8708
Revises: c3ae97472f64
Create Date: 2023-10-17 16:59:17.938376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1a545a8708'
down_revision = 'c3ae97472f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_path2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_path2')
        batch_op.drop_column('image_path1')

    # ### end Alembic commands ###
