"""empty message

Revision ID: 8e7fbf63bab6
Revises: 8b1a545a8708
Create Date: 2023-10-17 17:16:09.304129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7fbf63bab6'
down_revision = '8b1a545a8708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_path1')
        batch_op.drop_column('image_path2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_path1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
