"""empty message

Revision ID: 970e31e7ae1e
Revises: 7b10a687c66f
Create Date: 2023-10-18 14:58:14.248520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970e31e7ae1e'
down_revision = '7b10a687c66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
