"""empty message

Revision ID: 9db963f240d3
Revises: 8e7fbf63bab6
Create Date: 2023-10-17 17:47:36.524909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db963f240d3'
down_revision = '8e7fbf63bab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_path2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_path2')
        batch_op.drop_column('image_path1')

    # ### end Alembic commands ###
