"""empty message

Revision ID: c2ca9a3bbaf6
Revises: 970e31e7ae1e
Create Date: 2023-10-18 18:43:45.616603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ca9a3bbaf6'
down_revision = '970e31e7ae1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=180), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
